### ISSUE TITLE
Wiki or documentation

### ISSUE THREAD

**Issue by serhio7** [DataSciencePolimi/TweetAnalyser#17]
Hello! Do  you have any wiki or some kind or tutorial notebook?

**Comment by emrecalisir** [comment]
Hi, I've just started to create a wiki page upon your request, accessible from the Wiki section of the repository. Please check the wiki page a few days after from now. Best, Emre

**Comment by emrecalisir** [comment]
Please visit https://github.com/DataSciencePolimi/CSSforPolitics/wiki/Political-Stance-Classification-Wiki-Page for the explanation of Stance Classification pipeline
